spring:
  application:
    name: user_service
  datasource:
    url: ${HOSPITAL_APP_USER_SERVICE_DB_URL}
    username: ${HOSPITAL_APP_USER_SERVICE_DB_USER}
    password: ${HOSPITAL_APP_USER_SERVICE_DB_PASS}
    driver-class-name: ${HOSPITAL_APP_USER_SERVICE_DB_DRIVER}
  jpa:
    hibernate:
      ddl-auto: ${HOSPITAL_APP_USER_SERVICE_DB_DDL_AUTO}
    properties:
      hibernate:
        dialect: ${HOSPITAL_APP_USER_SERVICE_DB_DIALECT}
    show-sql: true
springdoc:
  swagger-ui:
    config-url: /users/v3/api-docs/swagger-config
    url: /users/v3/api-docs
grpc:
  server:
    port: 9090
    security:
      enabled: true
      certificate-chain: classpath:tls/user_service.crt
      private-key: classpath:tls/user_service_pkcs8.key
      trust-cert-collection: classpath:tls/ca.crt
      client-auth: REQUIRE


logging:
  level:
    io:
      grpc:
        netty: DEBUG
        internal: DEBUG