spring:
  application:
    name: user_service
  datasource:
    url: ${HOSPITAL_APP_USER_SERVICE_DB_URL}
    username: ${HOSPITAL_APP_USER_SERVICE_DB_USER}
    password: ${HOSPITAL_APP_USER_SERVICE_DB_PASS}
    driver-class-name: ${HOSPITAL_APP_USER_SERVICE_DB_DRIVER}
  jpa:
    hibernate:
      ddl-auto: ${HOSPITAL_APP_USER_SERVICE_DB_DDL_AUTO}
    properties:
      hibernate:
        dialect: ${HOSPITAL_APP_USER_SERVICE_DB_DIALECT}
    show-sql: true
springdoc:
  swagger-ui:
    config-url: /users/v3/api-docs/swagger-config
    url: /users/v3/api-docs
grpc:
  server:
    port: 9090
    security:
      enabled: true
      certificate-chain: ${HOSPITAL_APP_USER_SERVICE_CRT}
      private-key: ${HOSPITAL_APP_USER_SERVICE_KEY}
      trust-cert-collection: ${HOSPITAL_APP_USER_SERVICE_CA}
      client-auth: ${HOSPITAL_APP_USER_SERVICE_CLIENT_AUTH}

INITIAL_ADMIN_NAME: ${INITIAL_ADMIN_NAME}
INITIAL_ADMIN_USERNAME: ${INITIAL_ADMIN_USERNAME}
INITIAL_ADMIN_EMAIL: ${INITIAL_ADMIN_EMAIL}
INITIAL_ADMIN_CPF: ${INITIAL_ADMIN_CPF}
INITIAL_ADMIN_PASSWORD: ${INITIAL_ADMIN_PASSWORD}
