spring:
  application:
    name: user_service
  datasource:
    url: ${HOSPITAL_APP_USER_SERVICE_DB_URL}
    username: ${HOSPITAL_APP_USER_SERVICE_DB_USER}
    password: ${HOSPITAL_APP_USER_SERVICE_DB_PASS}
    driver-class-name: ${HOSPITAL_APP_USER_SERVICE_DB_DRIVER}
  jpa:
    hibernate:
      ddl-auto: ${HOSPITAL_APP_USER_SERVICE_DB_DDL_AUTO}
    properties:
      hibernate:
        dialect: ${HOSPITAL_APP_USER_SERVICE_DB_DIALECT}
    show-sql: true
springdoc:
  swagger-ui:
    config-url: /user-service/v3/api-docs/swagger-config
    url: /user-service/v3/api-docs
grpc:
  server:
    port: 9090
    security:
      enabled: false